"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1000
scan_timeout = 10

add_newline = false

format = """
$directory$git_branch$git_status
$character
"""

[character]
success_symbol = '[➜](purple)'
error_symbol = '[➜](red)'


[git_branch]
style = 'yellow'
format = ', [$branch]($style)'

[git_status]
style = 'red'
format = '[$all_status]($style)'

[directory]
truncation_length = 3
truncation_symbol = './'
style = "blue"
format = '[$path]($style)'
